//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// courses
namespace Symphony
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cours()
        {
            this.enrolls = new HashSet<enroll>();
        }

        [Display(Name = "Course Id")]
        [Required]
        public int c_id { get; set; }

        [Display(Name = "Course Name")]
        [Required]
       
        public string c_name { get; set; }

        [Display(Name = "Course Image")]
        [Required]
        public string c_image { get; set; }
        public HttpPostedFileBase imagefile { get; set; }


        [Display(Name = "Course Fees")]
        [Required]
        
        public int c_fees { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enroll> enrolls { get; set; }
    }
}

