//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class entance_exams
    {
        [Display(Name = "Roll Number")]
        [Required]
        public int roll_num { get; set; }

        [Display(Name = "Obtained Marks")]
        [Required]
        public int marks { get; set; }

        [Display(Name = "Course Id")]
        [Required]
        public int c_id { get; set; }

        [Display(Name = "Fees")]
        [Required]
        public int fees { get; set; }


        [Display(Name = "Student Name")]
        [Required]
        [DataType (DataType.Text)]
        public string s_name { get; set; }
        public Nullable<decimal> cell { get; set; }


        [Display(Name = "User Id")]
        [Required]
        public int user_id { get; set; }
    
        public virtual enroll enroll { get; set; }
    }
}
