//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class faq
    {
        public int f_id { get; set; }

        [Display(Name = "Questions")]
        [Required]
        public string q { get; set; }

        [Display(Name = "Answers")]
        [Required]
        public string a { get; set; }
    }
}
