//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities6 : DbContext
    {
        public Database1Entities6()
            : base("name=Database1Entities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<enroll> enrolls { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<video> videos { get; set; }
        public virtual DbSet<entance_exams> entance_exams { get; set; }
    }
}
