//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class register
    {
        public int Id { get; set; }

        [Display(Name = "UserName")]
        [Required]
        public string username { get; set; }

        [Display(Name = "Password")]
        [Required]
        [DataType (DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Full Name")]
        [Required]
        public string full_name { get; set; }

        [Display(Name = "Role Id")]
        [Required]
        public int role_id { get; set; }
    }
}
